[alias]
# This alias checks the lint
lint_check = "fmt --all -- --check"

# This alias formats the code
lint_fix = "fmt --all"

# This alias checks the code
check_code = "clippy --all-targets --all-features -- -D warnings"

[registries.mairie360]
index = "https://mairie360-eip.fr/cargo-index"

[net]
git-fetch-with-cli = true
