[alias]
# This alias checks the lint
lint_check = "fmt --all -- --check"

# This alias formats the code
lint_fix = "fmt --all"

# This alias checks the code
check_code = "clippy --all-targets --all-features -- -D warnings"

[registries]
github = { index = "https://github.com/mairie360/API_lib" }
