[alias]
# This alias checks the lint (clippy au niveau le plus strict, voir [lints.clippy] dans Cargo.toml)
lint_check = "clippy --all-targets --all-features -- -D warnings"

# This alias formats the code
lint_fix = "fmt --all"

# This alias checks the code
check_code = "clippy --all-targets --all-features -- -D warnings"

[registries.mairie360]
index = "https://github.com/mairie360/cargo-index"

[net]
git-fetch-with-cli = true
