name: API-Lib-CI

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  call-cicd:
    uses: mairie360/CICD/.github/workflows/cicd.yml@feat/MAIR-5-add-api-lib-cicd
    with:
      type: ci-back-lib
