name: Rust

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  call-cicd:
    uses: mairie360/CICD/.github/workflows/cicd.yml@feat/MAIR-5-add-api-lib-cicd
    with:
      type: back-lib
