name: Rust

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  call-cicd:
    uses: mairie360/CICD/.github/workflows/cicd.yml@feat/MAIR-5-add-api-lib-cicd
    secrets:
      CPANEL_API_TOKEN: ${{ secrets.CPANEL_API_TOKEN }}
      CPANEL_PASSWORD: ${{ secrets.CPANEL_PASSWORD }}
      CPANEL_SERVER: ${{ secrets.CPANEL_SERVER }}
      CPANEL_USERNAME: ${{ secrets.CPANEL_USERNAME }}
      DEPLOY_SSH_KEY: ${{ secrets.DEPLOY_SSH_KEY }}
      MAIRIE_360_DEPLOY_TOKEN: ${{ secrets.MAIRIE_360_DEPLOY_TOKEN }}
    with:
      type: cd-back-lib
